"""empty message

Revision ID: 09277d488117
Revises: 3cebfa1657b1
Create Date: 2025-06-27 16:46:43.974269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09277d488117'
down_revision = '3cebfa1657b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_name'), ['name'], unique=False)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planet_name'), ['name'], unique=False)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_name'))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planet_name'))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_name'))

    # ### end Alembic commands ###
